// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: application_template.proto

// Protobuf Java Version: 3.25.2
package com.rapidapp.applicationtemplate;

public final class ApplicationTemplateOuterClass {
  private ApplicationTemplateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:applicationtemplate.SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code applicationtemplate.SearchRequest}
   */
  public static final class SearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:applicationtemplate.SearchRequest)
      SearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_SearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest.class, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest)) {
        return super.equals(obj);
      }
      com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest other = (com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code applicationtemplate.SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:applicationtemplate.SearchRequest)
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_SearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest.class, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest.Builder.class);
      }

      // Construct using com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_SearchRequest_descriptor;
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest getDefaultInstanceForType() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest build() {
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest buildPartial() {
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest result = new com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest) {
          return mergeFrom((com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest other) {
        if (other == com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:applicationtemplate.SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:applicationtemplate.SearchRequest)
    private static final com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest();
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      @java.lang.Override
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApplicationTemplateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:applicationtemplate.ApplicationTemplate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code applicationtemplate.ApplicationTemplate}
   */
  public static final class ApplicationTemplate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:applicationtemplate.ApplicationTemplate)
      ApplicationTemplateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplicationTemplate.newBuilder() to construct.
    private ApplicationTemplate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplicationTemplate() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ApplicationTemplate();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.class, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate)) {
        return super.equals(obj);
      }
      com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate other = (com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code applicationtemplate.ApplicationTemplate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:applicationtemplate.ApplicationTemplate)
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.class, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder.class);
      }

      // Construct using com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplate_descriptor;
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate getDefaultInstanceForType() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.getDefaultInstance();
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate build() {
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate buildPartial() {
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate result = new com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate) {
          return mergeFrom((com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate other) {
        if (other == com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:applicationtemplate.ApplicationTemplate)
    }

    // @@protoc_insertion_point(class_scope:applicationtemplate.ApplicationTemplate)
    private static final com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate();
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplicationTemplate>
        PARSER = new com.google.protobuf.AbstractParser<ApplicationTemplate>() {
      @java.lang.Override
      public ApplicationTemplate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApplicationTemplate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApplicationTemplate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApplicationTemplateListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:applicationtemplate.ApplicationTemplateList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    java.util.List<com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate> 
        getItemsList();
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate getItems(int index);
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    java.util.List<? extends com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code applicationtemplate.ApplicationTemplateList}
   */
  public static final class ApplicationTemplateList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:applicationtemplate.ApplicationTemplateList)
      ApplicationTemplateListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplicationTemplateList.newBuilder() to construct.
    private ApplicationTemplateList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplicationTemplateList() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ApplicationTemplateList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplateList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplateList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList.class, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate> items_;
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    @java.lang.Override
    public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
     */
    @java.lang.Override
    public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList)) {
        return super.equals(obj);
      }
      com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList other = (com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code applicationtemplate.ApplicationTemplateList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:applicationtemplate.ApplicationTemplateList)
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplateList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplateList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList.class, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList.Builder.class);
      }

      // Construct using com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.internal_static_applicationtemplate_ApplicationTemplateList_descriptor;
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList getDefaultInstanceForType() {
        return com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList.getDefaultInstance();
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList build() {
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList buildPartial() {
        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList result = new com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList result) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
      }

      private void buildPartial0(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList) {
          return mergeFrom((com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList other) {
        if (other == com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate m =
                    input.readMessage(
                        com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.parser(),
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public java.util.List<com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder setItems(
          int index, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder setItems(
          int index, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder addItems(com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder addItems(
          int index, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder addItems(
          com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder addItems(
          int index, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public java.util.List<? extends com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.getDefaultInstance());
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.getDefaultInstance());
      }
      /**
       * <code>repeated .applicationtemplate.ApplicationTemplate items = 1;</code>
       */
      public java.util.List<com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplate.Builder, com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:applicationtemplate.ApplicationTemplateList)
    }

    // @@protoc_insertion_point(class_scope:applicationtemplate.ApplicationTemplateList)
    private static final com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList();
    }

    public static com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplicationTemplateList>
        PARSER = new com.google.protobuf.AbstractParser<ApplicationTemplateList>() {
      @java.lang.Override
      public ApplicationTemplateList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApplicationTemplateList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApplicationTemplateList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rapidapp.applicationtemplate.ApplicationTemplateOuterClass.ApplicationTemplateList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_applicationtemplate_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_applicationtemplate_SearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_applicationtemplate_ApplicationTemplate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_applicationtemplate_ApplicationTemplate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_applicationtemplate_ApplicationTemplateList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_applicationtemplate_ApplicationTemplateList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032application_template.proto\022\023applicatio" +
      "ntemplate\"\035\n\rSearchRequest\022\014\n\004name\030\001 \001(\t" +
      "\"#\n\023ApplicationTemplate\022\014\n\004name\030\001 \001(\t\"R\n" +
      "\027ApplicationTemplateList\0227\n\005items\030\001 \003(\0132" +
      "(.applicationtemplate.ApplicationTemplat" +
      "e2x\n\032ApplicationTemplateService\022Z\n\004List\022" +
      "\".applicationtemplate.SearchRequest\032,.ap" +
      "plicationtemplate.ApplicationTemplateLis" +
      "t\"\000BX\n com.rapidapp.applicationtemplateZ" +
      "4github.com/huseyinbabal/rapidapp/applic" +
      "ationtemplateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_applicationtemplate_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_applicationtemplate_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_applicationtemplate_SearchRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_applicationtemplate_ApplicationTemplate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_applicationtemplate_ApplicationTemplate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_applicationtemplate_ApplicationTemplate_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_applicationtemplate_ApplicationTemplateList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_applicationtemplate_ApplicationTemplateList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_applicationtemplate_ApplicationTemplateList_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
